env:
  global:
    - COVERALLS_REPO_TOKEN=BumoRc2SfzlkhNY55yEnJHdX6Y2oPfAvr

sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7

before_script:
  - chmod a+x gradlew

after_success:
  - ./gradlew jacocoTestReport coveralls

script:
  - ./gradlew build

script: ./gradlew clean build test jacocoTestReport